handlers= java.util.logging.ConsoleHandler
.level = SEVERE

org.hibernate.level = OFF
org.hibernate.SQL.level = OFF
org.hibernate.type.level = OFF
org.hibernate.tool.hbm2ddl.level = OFF

javax.persistence.level = OFF
