#Application config
#Sun Mar 29 01:12:32 EET 2026
AudioDevice=Voicemeeter Out B2 (VB-Audio Voicemeeter VAIO)
AutoAdapt=false
MinPrefResolution=720p
NextEp=false
RecordingsPath=C\:\\Users\\Peven\\Desktop
